### ISSUE TITLE
Command fails on *BSD

### ISSUE THREAD

**Issue by cachapa** [cachapa/RemoteGallery#1]
Reported on the blog entry:
Re command switches for ls the –indicator-style=slash is not supported on *BSD, use -p instead, bsd ls man page, should be supported on both.

Link: http://www.openbsd.org/cgi-bin/man.cgi?query=ls&apropos=0&sektion=0&manpath=OpenBSD+Current&arch=i386&format=html

**Comment by rcbarnes** [comment]
Patch to fix this is listed in issue #11.

**Comment by cachapa** [comment]
Closing this one
