### ISSUE TITLE
Feature request: delete file locally and remotely

### ISSUE THREAD

**Issue by gustafson** [cachapa/RemoteGallery#7]
Could you add a feature (implemented similar to the share feature) which deletes the file locally and also issues a ssh rm $filename to the remote location?  Perhaps rename would be another useful feature?  These would make remotegallery a somewhat competent photo manager as well as great gallery viewer.

**Comment by cachapa** [comment]
I don't think that anybody would want to use a mobile app as their main photo manager.

There are many arguments against this, but the strongest one for me is that I don't want to be responsible for bugs in RG deleting someone's important pictures by mistake.
