### ISSUE TITLE
String too long

### ISSUE THREAD

**Issue by danielholm** [cachapa/RemoteGallery#8]
Hi,

I followed your guide to set this up (I already have SSH connections to my server, never used Dropbear for it though) but I get that the string is too long.

The SSH connection seems alright when runnig the test connection in the client. But the row after that says:
/data/data/net.cachapa.remotegallery/files/ssh:
exited: string too long

What is that?

**Comment by cachapa** [comment]
Hi Daniel,

it seems to be exactly what it says: the string is too long.
The connections are always made in a one-off manner. That means that
it's a single string containing your server, username and the complete
path the the file or folder you're requesting.

It seems that your directory structure is too deep, and you're getting
that error.
Honestly I'd never seen that problem before, so I don't really know
how one could go about in fixing it.
If you're experienced with Android development, the project is open
source, so I would be glad to have contributions.

Cheers,

On 10 January 2012 12:25, Daniel Holm
reply@reply.github.com
wrote:

> Hi,
> 
> I followed your guide to set this up (I already have SSH connections to my server, never used Dropbear for it though) but I get that the string is too long.
> 
> The SSH connection seems alright when runnig the test connection in the client. But the row after that says:
> /data/data/net.cachapa.remotegallery/files/ssh:
> exited: string too long
> 
> What is that?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/cachapa/RemoteGallery/issues/8

## 

Daniel Cachapa

**Comment by danielholm** [comment]
Hi,

I see. But even if I remove the dir and just keep the root ("/"), the issue wont resolve.
Before I just used "/home/daniel". THat shouldn't be too deep, right?

I saw another guy having this issue in the comments at your tutorial page. He simply removed and added the host again (I think). Neither that wants to work..

I'd like to help, and I do want to start with some Android development, but I'm a real newbie when it comes to Android dev, even Java for that matter.

Alhough I might start of by your project since I will need a Android client for a backup and share service I've started developing.

**Comment by cachapa** [comment]
You're right, your folder structure seems to be short enough.

Did you try testing the connection by long-pressing on your server
configuration in the main screen?

On 10 January 2012 21:26, Daniel Holm
reply@reply.github.com
wrote:

> Hi,
> 
> I see. But even if I remove the dir and just keep the root ("/"), the issue wont resolve.
> Before I just used "/home/daniel". THat shouldn't be too deep, right?
> 
> I saw another guy having this issue in the comments at your tutorial page. He simply removed and added the host again (I think). Neither that wants to work..
> 
> I'd like to help, and I do want to start with some Android development, but I'm a real newbie when it comes to Android dev, even Java for that matter.
> 
> Alhough I might start of by your project since I will need a Android client for a backup and share service I've started developing.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/cachapa/RemoteGallery/issues/8#issuecomment-3436328

## 

Daniel Cachapa

**Comment by danielholm** [comment]
Yes, and that connection echos OK and then it says
/data/data/net.cachapa.remotegallery/files/ssh: exited string too long

Also I've tried putting my key directly in /sdcard.

Does the key have to have any file ending? I've trodd to bale it only "dss".
Den 10 jan 2012 23:32 skrev "cachapa" <
reply@reply.github.com

**Comment by danielholm** [comment]
You know what; it seems like theres even no actual data transfer. Using
ConnectBot I van connect to my servera, and it also shows some transfer
progress up in the top bar, next to the reception status.

Perhaps I should take a look at the auth.log
Den 11 jan 2012 01:02 skrev "Daniel Holm" admin@danielholm.se:

**Comment by danielholm** [comment]
Nope, auth.log dont show any connection after my initial. Looks like there
an issue before connecting.
Den 11 jan 2012 01:11 skrev "Daniel Holm" admin@danielholm.se:

**Comment by cachapa** [comment]
Is your key in the dropbeat format?
OpenSSH keys don't work and need to be converted .

## 

Daniel Cachapa
Sent from a mobile device
Am 11.01.2012 01:02 schrieb "Daniel Holm" <
reply@reply.github.com

**Comment by danielholm** [comment]
Yep, its dropbear. Just like your guide.
Den 11 jan 2012 01:35 skrev "cachapa" <
reply@reply.github.com

**Comment by cachapa** [comment]
Man I'm sorry but I'm out of ideas.
I'm not in my PC right now but maybe you could google for that error string
and dropbear.

It might be that your keyfile is malformed somehow, but again, it's really
hard to debug this remotely.

## 

Daniel Cachapa
Sent from a mobile device
Am 11.01.2012 02:10 schrieb "Daniel Holm" <
reply@reply.github.com

**Comment by danielholm** [comment]
Yeah, this is really wierd. Re-install wont work either..
I'll try a new key.

**Comment by danielholm** [comment]
Finally. I generated a new key and did everything over again. Now it works!

**Comment by cachapa** [comment]
Ah, great!
Now I know what that error is for :-)

Thanks.

On 11 January 2012 12:10, Daniel Holm
reply@reply.github.com
wrote:

> Finally. I generated a new key and did everything over again. Now it works!
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/cachapa/RemoteGallery/issues/8#issuecomment-3445038

## 

Daniel Cachapa

**Comment by adumont** [comment]
Did you find the cause of the error? I'm having the exact same issue with ssh. Been using the same command line for months just fine, so I know at least it should work... Must be an issue with my ssh binary maybe? 

I'm using ssh on Android.

EDIT: Tried another binary (v1.21.1-kk bionic (2013-11-24 11:52 +0100)) and it works just fine!. So it's the binary I guess.

**Comment by Byggvir** [comment]
I have the same issue when I want to connect from one router to another router. 
When I generate a key with dropbearkey ssh asks for a passphrase fpr dei private key. But you can't set a passphrase with dropbearkey. An emtpy password is a bad passphrase?

**Comment by cachapa** [comment]
This project is abandoned and I can barely remember details, so sorry if what I'm saying doesn't make sense.

Setting a password on the key is meant to protect the key itself. That is, if someone gets a copy of your key, a password makes it harder for them to actually use it.
As far as I know, the presence of a password plays no role in the security during the actual use of the key when communicating with a remote host.

The recommendation of setting an empty password is for convenience: you don't get asked for input every time you initiate a connection. As far as I remember, Remote Gallery doesn't even support interactive logins (i.e. it would hang on the password request, not knowing what to do).

If at any point you suspect that your key might have been copied, you can always just delete the public hash from your server and generate a new key pair.
